sudo: required

services:
    - docker

before_install:
    - docker build -t sannithrao/loginapp .

script:
    - docker run sannithrao/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push sannithrao/loginapp

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: docker-loginapp
    env: DockerLoginapp-env
    bucket_name: elasticbeanstalk-ap-south-1-781667749013
    bucket_path: docker-loginapp
    on:
       branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
